name: test_gura1
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'
#----------packages---------#

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  http : ^1.1.0
  url_launcher: ^6.1.12
  get: ^4.6.6
  get_storage: ^2.1.1
  logger: ^2.0.2+1
  native_splash_screen: ^2.1.0


#------ icons --------#
iconsax: ^0.0.8
cupertino_icons: ^1.0.8


#-----state_management-------#
get: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.2.1


flutter:
  uses-material-design: true
assets:
  -Assets/fonts
  -Assets/Icons/brands
  -Assets/images/on_boarding_images 
  -Assets/Logos



